apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-11-30T01:34:14Z"
  generation: 3
  labels:
    app: app-web
    app.kubernetes.io/component: tsuru-app
    app.kubernetes.io/instance: app-web
    app.kubernetes.io/managed-by: tsuru
    app.kubernetes.io/name: app
    tsuru.io/app-name: app
    tsuru.io/app-platform: python
    tsuru.io/app-pool: local
    tsuru.io/app-process: web
    tsuru.io/app-team: admin
    tsuru.io/is-build: "false"
    tsuru.io/is-isolated-run: "false"
    tsuru.io/is-routable: "true"
    tsuru.io/is-service: "true"
    tsuru.io/is-stopped: "false"
    tsuru.io/is-tsuru: "true"
  name: app-web
  namespace: default
  resourceVersion: "4461287"
  uid: 52fcd1c7-5159-45c0-a300-b9f8dde57021
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tsuru.io/app-name: app
      tsuru.io/app-process: web
      tsuru.io/is-build: "false"
      tsuru.io/is-isolated-run: "false"
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        tsuru.io/app-name: app
        tsuru.io/app-platform: python
        tsuru.io/app-pool: local
        tsuru.io/app-process: web
        tsuru.io/app-team: admin
        tsuru.io/app-version: "4"
        tsuru.io/is-build: "false"
        tsuru.io/is-isolated-run: "false"
        tsuru.io/is-routable: "true"
        tsuru.io/is-tsuru: "true"
    spec:
      containers:
      - command:
        - /bin/sh
        - -lc
        - '[ -d /home/application/current ] && cd /home/application/current; exec
          $0 "$@"'
        - nginx
        - -g
        - daemon off;
        env:
        - name: TSURU_APPDIR
          value: /home/application/current
        - name: TSURU_APPNAME
          value: app
        - name: TSURU_SERVICES
          value: '{}'
        - name: TSURU_PROCESSNAME
          value: web
        - name: TSURU_APPVERSION
          value: "4"
        - name: TSURU_HOST
          value: http://tsuru-api.tsuru-system.svc.cluster.local
        - name: PORT_web
          value: "80"
        image: tsuru-registry.tsuru-system.svc.cluster.local/app-app:v4
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10 || true
        name: app-web
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            ephemeral-storage: 100Mi
            memory: 256Mi
          requests:
            cpu: 100m
            ephemeral-storage: "0"
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      serviceAccount: app-app
      serviceAccountName: app-app
      subdomain: app-web-units
      terminationGracePeriodSeconds: 40
status:
  conditions:
  - lastTransitionTime: "2024-11-30T01:34:14Z"
    lastUpdateTime: "2024-11-30T03:42:39Z"
    message: ReplicaSet "app-web-7dcc4d59b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-11-30T03:42:40Z"
    lastUpdateTime: "2024-11-30T03:42:40Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
