apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-01-02T02:39:39Z"
  generation: 1
  labels:
    app: education-web
    app.kubernetes.io/component: tsuru-app
    app.kubernetes.io/instance: education-web
    app.kubernetes.io/managed-by: tsuru
    app.kubernetes.io/name: education
    tsuru.io/app-name: education
    tsuru.io/app-platform: python
    tsuru.io/app-pool: local
    tsuru.io/app-process: web
    tsuru.io/app-team: admin
    tsuru.io/is-build: "false"
    tsuru.io/is-isolated-run: "false"
    tsuru.io/is-routable: "true"
    tsuru.io/is-service: "true"
    tsuru.io/is-stopped: "false"
    tsuru.io/is-tsuru: "true"
  name: education-web
  namespace: default
  resourceVersion: "15856234"
  uid: b615240c-f3c3-4b15-bdfb-c96c3476feb8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tsuru.io/app-name: education
      tsuru.io/app-process: web
      tsuru.io/is-build: "false"
      tsuru.io/is-isolated-run: "false"
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        tsuru.io/app-name: education
        tsuru.io/app-platform: python
        tsuru.io/app-pool: local
        tsuru.io/app-process: web
        tsuru.io/app-team: admin
        tsuru.io/app-version: "1"
        tsuru.io/is-build: "false"
        tsuru.io/is-isolated-run: "false"
        tsuru.io/is-routable: "true"
        tsuru.io/is-tsuru: "true"
    spec:
      containers:
        - command:
            - /bin/sh
            - -lc
            - '[ -d /home/application/current ] && cd /home/application/current; exec
              $0 "$@"'
            - /docker-entrypoint.sh
            - nginx
            - -g
            - daemon off;
          env:
            - name: TSURU_APPDIR
              value: /home/application/current
            - name: TSURU_APPNAME
              value: education
            - name: TSURU_SERVICES
              value: "{}"
            - name: TSURU_PROCESSNAME
              value: web
            - name: TSURU_APPVERSION
              value: "1"
            - name: TSURU_HOST
              value: http://tsuru-api.tsuru-system.svc.cluster.local
            - name: PORT_web
              value: "80"
          image: tsuru-registry.tsuru-system.svc.cluster.local/app-education:v1
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10 || true
          name: education-web
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              ephemeral-storage: 100Mi
              memory: 256Mi
            requests:
              cpu: 100m
              ephemeral-storage: "0"
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      serviceAccount: app-education
      serviceAccountName: app-education
      subdomain: education-web-units
      terminationGracePeriodSeconds: 40
status:
  conditions:
    - lastTransitionTime: "2025-01-02T02:39:39Z"
      lastUpdateTime: "2025-01-02T02:39:43Z"
      message: ReplicaSet "education-web-5594567c86" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-01-02T02:50:46Z"
      lastUpdateTime: "2025-01-02T02:50:46Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
